
env = "production"
title = "Christoffer Moesgaard"
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowPostNavLinks = false
ShowBreadCrumbs = false
ShowCodeCopyButtons = true
ShowWordCount = false
UseHugoToc = false
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

[profileMode]
enabled = true
title = "Christoffer Moesgaard"
imageUrl = "images/avatar.jpg"

[[profileMode.buttons]]
name = "Posts"
url = "posts"

[[profileMode.buttons]]
name = "CV"
url = "https://registry.jsonresume.org/cmoesgaard"

[[socialIcons]]
name = "email"
url = "mailto:christoffer@moesgaard.dev"

[[socialIcons]]
name = "github"
url = "https://github.com/cmoesgaard"

[[socialIcons]]
name = "gitlab"
url = "https://gitlab.com/cmoesgaard"

[[socialIcons]]
name = "linkedin"
url = "https://linkedin.com/in/cmoesgaard"
