[build]
publish = "public"
command = "hugo --gc --minify"

# [build.environment]
# HUGO_VERSION = "0.36"

[context.deploy-preview]
command = "hugo -b $DEPLOY_URL"

[context.branch-deploy]
command = "hugo -b $DEPLOY_URL"
